version: '3'

services:
  db:
    image: postgis/postgis:14-master
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=ske
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpwd
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    volumes:
      - .:/code/
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  pg-data: